version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: web_scraper_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  sidekiq:
    environment:
      - REDIS_URL=redis://redis:6379/0
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis

  web:
    environment:
      - REDIS_URL=redis://redis:6379/0
    build: .
    command: rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
