default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: db
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: web_scraper_development
